### ISSUE TITLE
Create spec for test network to deploy changes and deploy then

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/l14-deploy-node-gcloud#1]

**Comment by frozeman** [comment]
@blazejkrzak can you make a PR creating a new `l15` branch.
- Change the readme to our new project `l15-testnet`
- change the chain.spec to chain ID: `23`
- lets remove the PoA smart contracts, and make a simple fixed validator setup for now

**Comment by blazejkrzak** [comment]
Reminder: It will be good to use gcloud sdk when we will set up l15 again

**Comment by mxmar** [comment]
Script has been improved in https://github.com/lukso-network/l16-deploy-node-gcloud/issues/1 issue (repo).

`l15` was manually prepared by GCP dashboard.
